//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FExcel.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FExcel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID	Файл	Книга	Структура	Лист	Шаблон	СмещениеГод	Группа	ОГ	Опция	Доля
        ///1	D:\Sergey\МАКРОСЫ\220623 ExcelDNA\Samples\SamplesADOData\Folder1\test1.xlsx	test1.xlsx		Sheet1	ТЕСТ_ШАБЛОН		РиД	ОГ1	Мест1	1
        ///2	D:\Sergey\МАКРОСЫ\220623 ExcelDNA\Samples\SamplesADOData\Folder1\test1.xlsx	test1.xlsx		Sheet2	ТЕСТ_ШАБЛОН		РиД	ОГ1	Мест2	1
        ///3	D:\Sergey\МАКРОСЫ\220623 ExcelDNA\Samples\SamplesADOData\Folder1\test1.xlsx	test1.xlsx		Sheet3	ТЕСТ_ШАБЛОН		РиД	ОГ1	Мест3	1
        ///4	D:\Sergey\МАКРОСЫ\220623 ExcelDNA\Samples\SamplesADOData\Fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string LoadListTable {
            get {
                return ResourceManager.GetString("LoadListTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID	Параметр	МФСО	Выбор	П5	ФормаПроизв	Compare
        ///1	Параметр1	1	1	G1		
        ///2	Параметр2	1	0	G2		
        ///3	Параметр3	1	1	G3		G6
        ///4	Параметр4	1	0	G4		
        ///5	Параметр5	1	1	G5		
        ///6	Параметр6	1	0	G6		G7
        ///7	Параметр7	1	1	G7		
        ///8	Параметр8	1	0	G8		
        ///9	Параметр9	1	1	G9	J9	G8
        ///10	Параметр10	1	0	G10	J10	
        ///11	Параметр11	1	0	G11	J11	
        ///12	Параметр12	1	0	G12	J12	G9
        ///13	Параметр13	1	0	G13	J13	
        ///14	Параметр14	1	0	G14	J14	
        ///15	Параметр15	1	0	G15	J15	G10
        ///16	Параметр16	0	0	G16		
        ///17	Параметр17	0	0	G17		
        ///18	Параметр18	0	0	G18		G11
        ///19	Парам [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ParamsTable {
            get {
                return ResourceManager.GetString("ParamsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаблон	Маска	ПерваяЯчейка
        ///П5	*|*|A5|*ggg*	F4
        ///ФормаПроизв	*|*|J5|*rr*	J8
        ///Compare	*|*|P2|*SSS*	K7
        ///.
        /// </summary>
        internal static string TemplatesTable {
            get {
                return ResourceManager.GetString("TemplatesTable", resourceCulture);
            }
        }
    }
}
